services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./app:/backend/app